### ISSUE TITLE
I'm getting different AAID if using any app cloner apps like DO Multiple Accounts - Infinite Parallel Clone App, Parallel Space - Multiple accounts & Two face ect.

### ISSUE THREAD

**Issue by devVinit** [sparkfabrik/sparkfabrik-react-native-idfa-aaid#28]
Hey,

I'm getting different AAID in my app if one is opened normally and one opened in the parrel space app (app cloner).

**Comment by edodusi** [comment]
Hey @devVinit, I don't know how app cloner works, do you have any detail?

**Comment by devVinit** [comment]
hey @edodusi, Yes so it basically helps in running two instances of the app on one device, people use it for running multiple accounts. 

https://www.youtube.com/watch?v=FHESoFZ9zBg

**Comment by edodusi** [comment]
@devVinit so apparently it's like you have two users on the same device, so having different AAIDs is correct.

**Comment by devVinit** [comment]
Yeah, we should get two AAIDs but we don't. It was said to be unique but got duplicate in both cases while running app

**Comment by edodusi** [comment]
Sorry @devVinit I'm not sure I understand the problem you're facing. This module is a wrapper around the native call to get IDFA and AAID, so the result you get is the same you would get if you directly call the native API.

So there's no issue with the module itself, it's just behaving the way it should.

**Comment by devVinit** [comment]
We were using it as a unique device id, but when uses clone the app we get different AAIDs. But according to going through google android docs I'm able to understand that AAIDs will change in case of that.
