### ISSUE TITLE
types path is wrong on package.json 

### ISSUE THREAD

**Issue by PadovaY** [sparkfabrik/sparkfabrik-react-native-idfa-aaid#54]
hey, thank you for this package 🙂 
I updated the package to version 1.0.0, and typescript started showing the next error: 

`Could not find a declaration file for module '@sparkfabrik/react-native-idfa-aaid'. '**/@sparkfabrik/react-native-idfa-aaid/lib/commonjs/index.js' implicitly has an 'any' type.
  Try "npm i --save-dev @types/sparkfabrik__react-native-idfa-aaid" if it exists or add a new declaration (.d.ts) file containing "declare module '@sparkfabrik/react-native-idfa-aaid';"ts(7016)
`

it seems the issue is the types path in the package.json file: 
https://github.com/sparkfabrik/sparkfabrik-react-native-idfa-aaid/blob/e799db0be2fd6fb81ea8f16cb5abc6d1efa3a9de/package.json#L7

as it should be: 

```
"types": "lib/typescript/index.d.ts",
```

can you release a quick patch for this? 
thank you 🙏

**Comment by edodusi** [comment]
Hey @PadovaY, which typescript version are you using?

**Comment by PadovaY** [comment]
hey @edodusi, I'm using typescript version 4.9.5

**Comment by edodusi** [comment]
@PadovaY can you check latest 1.0.1 version?

**Comment by PadovaY** [comment]
@edodusi works awesome now, thanks!
