### ISSUE TITLE
Tracking not determined (iOS)

### ISSUE THREAD

**Issue by exzos28** [sparkfabrik/sparkfabrik-react-native-idfa-aaid#58]
Hello, on the first start of the application, I sometimes get the error "Tracking not determined". What could be the reason for this?

**Comment by exzos28** [comment]
After doing some research, I found that this happens when I call a request to send notifications, and then I call getAdvertisingInfo

**Comment by edodusi** [comment]
hello @exzos28, I suspect this maybe an issue with your code rather than something related to the module itself, do you have some other ideas?

**Comment by exzos28** [comment]
@edodusi Hi, I've discovered a very strange behavior on iOS. If several permissions are called in a row, the 3rd and next are not displayed. It is enough to have a timeout of 500ms between them, and then everything works fine. That's weird.
