### ISSUE TITLE
Upgrade  google ads identifier library to 19.3.0+ as google is rejecting apps with lower version

### ISSUE THREAD

**Issue by shivamarujolla** [sparkfabrik/sparkfabrik-react-native-idfa-aaid#62]
Error
The developer of Google Mobile Ads (GMA) SDK (com.google.android.gms:play-services-ads) has reported version 18.0.1 as outdated. You must upgrade to a newer version (19.3.0+) before you can publish a new release to production.
Learn more about the SDKs that you're using and make informed SDK choices with Google Play SDK Index.

**Comment by bukhari-flip** [comment]
I think this library doesn't use [`com.google.android.gms:play-services-ads`](https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads), instead the [`com.google.android.gms:play-services-ads-identifier`](https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads-identifier) version (18.0.1) still supported.

**Comment by edodusi** [comment]
@bukhari-flip is right. And @shivamarujolla please try to be nicer when you open issues on open source libraries, everyone is tryin to do their best here

**Comment by shivamarujolla** [comment]
> @bukhari-flip is right. And @shivamarujolla please try to be nicer when you open issues on open source libraries, everyone is tryin to do their best here

Hey sorry if it felt that way my intension was never to hurt anyone i just copy pasted the error google play console showed me. i wanted to make the title as short as possible so its easily understandable. i will be more diligent next time.

**Comment by edodusi** [comment]
thanks @shivamarujolla, don't worry
